### ISSUE TITLE
Just an enquiry

### ISSUE THREAD

**Issue by morizin** [kentaroy47/Kaggle-PANDA-1st-place-solution#3]
It's not an issue it's just an enquiry . That the labels are 0,1,2,3,4,5 that is 6 in no. 
But I could see that your model output_dim is 5

I saw you using accumulation labelling that is

If class is 3: the label is [1.0,1.0,1.0,0,0] which is only 5 in Len
Why don't you use 6 labels

**Comment by kentaroy47** [comment]
@morizin 
Yes you can solve this task as a classification with 6 classes, as you state.

However in the competition, the score was actually better if you solve it as a multi-label regression problem with 5 outputs e.g. [1.0,1.0,0,0,] and simply sum the output to get the final grading. Hope that this will clear your question.
